const arrayInt = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
console.log(arrayInt.length);
console.log(arrayInt);
console.log(arrayInt.slice(_));
console.log(arrayInt.slice(__));
console.log(arrayInt.slice(_,_));
console.log(arrayInt.slice(__,__));
console.log(arrayInt.slice(_, arrayInt.________));
console.log(arrayInt.slice(_));
console.log(arrayInt.slice(__, arrayInt.______));
console.log(arrayInt.slice(__, __));
